### ISSUE TITLE
small syantax error

### ISSUE THREAD

**Issue by siddharth-kp** [pavitrakumar78/Python-OpenCV-Paint#2]
File "E:\projects\Python-OpenCV-Paint\Paint.py", line 65
    print "x:",cx,"y:",cy
    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by pavitrakumar78** [comment]
This is 8 years old... it was written in py2... 
> Did you mean print(...)

No.
